name: Build and Release SnapSteam

on:
  push:
    tags:
      - 'v*'  # 例如 v1.0.0 才会触发
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Get version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          npm version $VERSION --no-git-tag-version

      - name: Create build directory and entitlements file
        run: |
          mkdir -p build
          cat > build/entitlements.mac.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>com.apple.security.cs.allow-jit</key>
              <true/>
              <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
              <true/>
              <key>com.apple.security.cs.disable-library-validation</key>
              <true/>
              <key>com.apple.security.cs.disable-executable-page-protection</key>
              <true/>
              <key>com.apple.security.automation.apple-events</key>
              <true/>
              <key>com.apple.security.files.user-selected.read-write</key>
              <true/>
              <key>com.apple.security.files.downloads.read-write</key>
              <true/>
            </dict>
          </plist>
          EOF

      - name: Clean release directory
        run: rm -rf release/

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        continue-on-error: false

      - name: Package for mac (arm64)
        run: npm run package:mac
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}  

      - name: Package for mac (intel)
        run: npm run package:mac:intel
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}             

      - name: Verify artifacts
        run: |
          ls -la release/
          # 添加文件大小检查等验证步骤

      - name: Upload mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-artifacts
          path: |
            release/SnapSteam-*-arm64.dmg
            release/SnapSteam-*-x64.dmg

  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get version from tag
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          echo "VERSION=$version" >> $env:GITHUB_ENV
          npm version $version --no-git-tag-version

      - name: Clean release directory
        run: Remove-Item -Recurse -Force release -ErrorAction SilentlyContinue

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Package for Windows
        run: npm run package:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}             

      - name: Upload win artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-artifacts
          path: |
            release/SnapSteam-*-x64.exe

  release:
    needs: [build-mac, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

